spring:
  application:
    name: salesmanager-customer
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create